sonar.projectKey=O1egKovtun_lms_project
sonar.organization=o1egkovtun
sonar.projectName=LMS Platform
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
sonar.sourceEncoding=UTF-8
